services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017

  mail-server:
    image: mail-server:1.0
    volumes:
      - 'D:/My Projects/mail-server:/mail-server'

  dns-server:
    image: dns-server:1.0
    ports:
      - 53:53
    volumes:
      - 'D:/My Projects/my-dns-server:/dns-server'
